"""
Signal history API routes.

Exposes the log of valuation signals generated by the report builder,
with lazily-computed price_change_pct so callers can see how each
signal performed since it was issued.
"""

from typing import Optional

from fastapi import APIRouter, HTTPException

from backend.api.schemas import SignalHistoryItem, SignalHistoryResponse
from backend.log import logger

router = APIRouter(prefix="/signals", tags=["signals"])


def _enrich_with_price_change(
    rows: list[dict],
) -> list[SignalHistoryItem]:
    """Attach current price_change_pct to each row using cached price data."""
    from backend.data.storage import load_price_data

    price_cache: dict[str, Optional[float]] = {}
    items: list[SignalHistoryItem] = []

    for row in rows:
        ticker = row["ticker"]
        if ticker not in price_cache:
            try:
                price_df = load_price_data(ticker)
                price_cache[ticker] = (
                    float(price_df["Close"].iloc[-1])
                    if price_df is not None and not price_df.empty
                    else None
                )
            except Exception:
                price_cache[ticker] = None

        current_price = price_cache[ticker]
        actual_price = row["actual_price_at_signal"]

        price_change_pct = None
        if current_price is not None and actual_price:
            price_change_pct = round(
                (current_price - actual_price) / actual_price * 100, 2
            )

        items.append(SignalHistoryItem(
            id=row["id"],
            ticker=row["ticker"],
            signal=row["signal"],
            confidence_score=row["confidence_score"],
            model_predicted_price=row["model_predicted_price"],
            actual_price_at_signal=row["actual_price_at_signal"],
            created_at=row["created_at"],
            price_change_pct=price_change_pct,
        ))

    return items


@router.get("/history", response_model=SignalHistoryResponse)
async def get_signal_history(ticker: Optional[str] = None):
    """
    Retrieve signal history with lazy price_change_pct.

    - **?ticker=AAPL** — last 90 days of signals for that ticker, newest first.
    - *(no ticker)* — most recent signal per ticker across the entire watchlist.
    """
    from backend.data.storage import get_signal_history as _fetch

    try:
        if ticker:
            rows = _fetch(ticker=ticker.upper(), days=90)
        else:
            rows = _fetch(latest_per_ticker=True)

        items = _enrich_with_price_change(rows)
        return SignalHistoryResponse(items=items, count=len(items))

    except Exception as e:
        logger.error("Signal history fetch failed: {}", e)
        raise HTTPException(status_code=500, detail=str(e))
