// Common US stocks and ETFs for autocomplete suggestions
export const TICKER_LIST = [
  // ── Mega-cap Tech ──────────────────────────────────────────
  { ticker: 'AAPL', name: 'Apple Inc.' },
  { ticker: 'MSFT', name: 'Microsoft Corp.' },
  { ticker: 'NVDA', name: 'NVIDIA Corp.' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. (Class A)' },
  { ticker: 'GOOG', name: 'Alphabet Inc. (Class C)' },
  { ticker: 'AMZN', name: 'Amazon.com Inc.' },
  { ticker: 'META', name: 'Meta Platforms Inc.' },
  { ticker: 'TSLA', name: 'Tesla Inc.' },
  { ticker: 'AVGO', name: 'Broadcom Inc.' },
  { ticker: 'ORCL', name: 'Oracle Corp.' },
  { ticker: 'IBM', name: 'IBM Corp.' },
  { ticker: 'HPQ', name: 'HP Inc.' },
  { ticker: 'HPE', name: 'Hewlett Packard Enterprise' },
  { ticker: 'DELL', name: 'Dell Technologies' },
  { ticker: 'ACN', name: 'Accenture PLC' },
  { ticker: 'INFY', name: 'Infosys Ltd.' },
  { ticker: 'WIT', name: 'Wipro Ltd.' },
  // ── Semiconductors ─────────────────────────────────────────
  { ticker: 'AMD', name: 'Advanced Micro Devices' },
  { ticker: 'INTC', name: 'Intel Corp.' },
  { ticker: 'QCOM', name: 'Qualcomm Inc.' },
  { ticker: 'TXN', name: 'Texas Instruments' },
  { ticker: 'MU', name: 'Micron Technology' },
  { ticker: 'AMAT', name: 'Applied Materials' },
  { ticker: 'LRCX', name: 'Lam Research' },
  { ticker: 'KLAC', name: 'KLA Corp.' },
  { ticker: 'ASML', name: 'ASML Holding' },
  { ticker: 'TSM', name: 'Taiwan Semiconductor' },
  { ticker: 'ARM', name: 'Arm Holdings' },
  { ticker: 'MRVL', name: 'Marvell Technology' },
  { ticker: 'ON', name: 'ON Semiconductor' },
  { ticker: 'SWKS', name: 'Skyworks Solutions' },
  { ticker: 'MPWR', name: 'Monolithic Power Systems' },
  { ticker: 'NXPI', name: 'NXP Semiconductors' },
  { ticker: 'STX', name: 'Seagate Technology' },
  { ticker: 'WDC', name: 'Western Digital' },
  // ── Software & Cloud ───────────────────────────────────────
  { ticker: 'CRM', name: 'Salesforce Inc.' },
  { ticker: 'ADBE', name: 'Adobe Inc.' },
  { ticker: 'NOW', name: 'ServiceNow Inc.' },
  { ticker: 'SNOW', name: 'Snowflake Inc.' },
  { ticker: 'PLTR', name: 'Palantir Technologies' },
  { ticker: 'NET', name: 'Cloudflare Inc.' },
  { ticker: 'DDOG', name: 'Datadog Inc.' },
  { ticker: 'MDB', name: 'MongoDB Inc.' },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings' },
  { ticker: 'ZS', name: 'Zscaler Inc.' },
  { ticker: 'PANW', name: 'Palo Alto Networks' },
  { ticker: 'FTNT', name: 'Fortinet Inc.' },
  { ticker: 'MSCI', name: 'MSCI Inc.' },
  { ticker: 'WDAY', name: 'Workday Inc.' },
  { ticker: 'HUBS', name: 'HubSpot Inc.' },
  { ticker: 'ZM', name: 'Zoom Video Communications' },
  { ticker: 'TEAM', name: 'Atlassian Corp.' },
  { ticker: 'OKTA', name: 'Okta Inc.' },
  { ticker: 'TWLO', name: 'Twilio Inc.' },
  { ticker: 'DOCU', name: 'DocuSign Inc.' },
  { ticker: 'BILL', name: 'BILL Holdings' },
  { ticker: 'GTLB', name: 'GitLab Inc.' },
  { ticker: 'PATH', name: 'UiPath Inc.' },
  { ticker: 'AI', name: 'C3.ai Inc.' },
  { ticker: 'SMAR', name: 'Smartsheet Inc.' },
  { ticker: 'APPN', name: 'Appian Corp.' },
  { ticker: 'ESTC', name: 'Elastic N.V.' },
  { ticker: 'CFLT', name: 'Confluent Inc.' },
  { ticker: 'MSTR', name: 'MicroStrategy Inc.' },
  // ── Internet & Consumer Tech ───────────────────────────────
  { ticker: 'UBER', name: 'Uber Technologies' },
  { ticker: 'LYFT', name: 'Lyft Inc.' },
  { ticker: 'ABNB', name: 'Airbnb Inc.' },
  { ticker: 'DASH', name: 'DoorDash Inc.' },
  { ticker: 'COIN', name: 'Coinbase Global' },
  { ticker: 'RBLX', name: 'Roblox Corp.' },
  { ticker: 'SPOT', name: 'Spotify Technology' },
  { ticker: 'NFLX', name: 'Netflix Inc.' },
  { ticker: 'DIS', name: 'Walt Disney Co.' },
  { ticker: 'CMCSA', name: 'Comcast Corp.' },
  { ticker: 'CHTR', name: 'Charter Communications' },
  { ticker: 'T', name: 'AT&T Inc.' },
  { ticker: 'VZ', name: 'Verizon Communications' },
  { ticker: 'TMUS', name: 'T-Mobile US Inc.' },
  { ticker: 'PINS', name: 'Pinterest Inc.' },
  { ticker: 'SNAP', name: 'Snap Inc.' },
  { ticker: 'TTWO', name: 'Take-Two Interactive' },
  { ticker: 'EA', name: 'Electronic Arts' },
  { ticker: 'ATVI', name: 'Activision Blizzard' },
  { ticker: 'NTES', name: 'NetEase Inc.' },
  { ticker: 'BIDU', name: 'Baidu Inc.' },
  { ticker: 'BABA', name: 'Alibaba Group' },
  { ticker: 'JD', name: 'JD.com Inc.' },
  { ticker: 'PDD', name: 'PDD Holdings' },
  { ticker: 'SE', name: 'Sea Limited' },
  { ticker: 'MELI', name: 'MercadoLibre Inc.' },
  // ── Financials ─────────────────────────────────────────────
  { ticker: 'BRK.B', name: 'Berkshire Hathaway (B)' },
  { ticker: 'BRK.A', name: 'Berkshire Hathaway (A)' },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.' },
  { ticker: 'BAC', name: 'Bank of America' },
  { ticker: 'WFC', name: 'Wells Fargo & Co.' },
  { ticker: 'GS', name: 'Goldman Sachs' },
  { ticker: 'MS', name: 'Morgan Stanley' },
  { ticker: 'C', name: 'Citigroup Inc.' },
  { ticker: 'USB', name: 'U.S. Bancorp' },
  { ticker: 'PNC', name: 'PNC Financial Services' },
  { ticker: 'TFC', name: 'Truist Financial' },
  { ticker: 'COF', name: 'Capital One Financial' },
  { ticker: 'DFS', name: 'Discover Financial Services' },
  { ticker: 'AXP', name: 'American Express' },
  { ticker: 'V', name: 'Visa Inc.' },
  { ticker: 'MA', name: 'Mastercard Inc.' },
  { ticker: 'PYPL', name: 'PayPal Holdings' },
  { ticker: 'SQ', name: 'Block Inc.' },
  { ticker: 'BLK', name: 'BlackRock Inc.' },
  { ticker: 'SCHW', name: 'Charles Schwab' },
  { ticker: 'ICE', name: 'Intercontinental Exchange' },
  { ticker: 'CME', name: 'CME Group' },
  { ticker: 'NDAQ', name: 'Nasdaq Inc.' },
  { ticker: 'CBOE', name: 'Cboe Global Markets' },
  { ticker: 'MUFG', name: 'Mitsubishi UFJ Financial' },
  { ticker: 'DB', name: 'Deutsche Bank' },
  { ticker: 'UBS', name: 'UBS Group' },
  { ticker: 'CS', name: 'Credit Suisse' },
  { ticker: 'RY', name: 'Royal Bank of Canada' },
  { ticker: 'TD', name: 'Toronto-Dominion Bank' },
  { ticker: 'BNS', name: 'Bank of Nova Scotia' },
  { ticker: 'ALLY', name: 'Ally Financial' },
  { ticker: 'SYF', name: 'Synchrony Financial' },
  { ticker: 'FITB', name: 'Fifth Third Bancorp' },
  { ticker: 'RF', name: 'Regions Financial' },
  { ticker: 'HBAN', name: 'Huntington Bancshares' },
  { ticker: 'KEY', name: 'KeyCorp' },
  { ticker: 'CFG', name: 'Citizens Financial Group' },
  { ticker: 'MTB', name: 'M&T Bank Corp.' },
  { ticker: 'FRC', name: 'First Republic Bank' },
  { ticker: 'SIVB', name: 'SVB Financial Group' },
  // ── Insurance ──────────────────────────────────────────────
  { ticker: 'MET', name: 'MetLife Inc.' },
  { ticker: 'PRU', name: 'Prudential Financial' },
  { ticker: 'AFL', name: 'Aflac Inc.' },
  { ticker: 'ALL', name: 'Allstate Corp.' },
  { ticker: 'TRV', name: 'Travelers Companies' },
  { ticker: 'PGR', name: 'Progressive Corp.' },
  { ticker: 'CB', name: 'Chubb Ltd.' },
  { ticker: 'MMC', name: 'Marsh & McLennan' },
  { ticker: 'AON', name: 'Aon PLC' },
  // ── Healthcare ─────────────────────────────────────────────
  { ticker: 'UNH', name: 'UnitedHealth Group' },
  { ticker: 'JNJ', name: 'Johnson & Johnson' },
  { ticker: 'LLY', name: 'Eli Lilly and Co.' },
  { ticker: 'ABBV', name: 'AbbVie Inc.' },
  { ticker: 'MRK', name: 'Merck & Co.' },
  { ticker: 'PFE', name: 'Pfizer Inc.' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific' },
  { ticker: 'ABT', name: 'Abbott Laboratories' },
  { ticker: 'DHR', name: 'Danaher Corp.' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb' },
  { ticker: 'AMGN', name: 'Amgen Inc.' },
  { ticker: 'GILD', name: 'Gilead Sciences' },
  { ticker: 'ISRG', name: 'Intuitive Surgical' },
  { ticker: 'MRNA', name: 'Moderna Inc.' },
  { ticker: 'BIIB', name: 'Biogen Inc.' },
  { ticker: 'REGN', name: 'Regeneron Pharmaceuticals' },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals' },
  { ticker: 'HCA', name: 'HCA Healthcare' },
  { ticker: 'CVS', name: 'CVS Health Corp.' },
  { ticker: 'CI', name: 'Cigna Group' },
  { ticker: 'ELV', name: 'Elevance Health' },
  { ticker: 'HUM', name: 'Humana Inc.' },
  { ticker: 'CNC', name: 'Centene Corp.' },
  { ticker: 'MOH', name: 'Molina Healthcare' },
  { ticker: 'MCK', name: 'McKesson Corp.' },
  { ticker: 'ABC', name: 'AmerisourceBergen' },
  { ticker: 'CAH', name: 'Cardinal Health' },
  { ticker: 'BAX', name: 'Baxter International' },
  { ticker: 'BDX', name: 'Becton Dickinson' },
  { ticker: 'BSX', name: 'Boston Scientific' },
  { ticker: 'EW', name: 'Edwards Lifesciences' },
  { ticker: 'MDT', name: 'Medtronic PLC' },
  { ticker: 'SYK', name: 'Stryker Corp.' },
  { ticker: 'ZBH', name: 'Zimmer Biomet' },
  { ticker: 'IDXX', name: 'IDEXX Laboratories' },
  { ticker: 'IQV', name: 'IQVIA Holdings' },
  { ticker: 'DGX', name: 'Quest Diagnostics' },
  { ticker: 'LH', name: 'Labcorp' },
  { ticker: 'ILMN', name: 'Illumina Inc.' },
  { ticker: 'HOLX', name: 'Hologic Inc.' },
  { ticker: 'DXCM', name: 'DexCom Inc.' },
  { ticker: 'ALGN', name: 'Align Technology' },
  { ticker: 'RMD', name: 'ResMed Inc.' },
  { ticker: 'ZTS', name: 'Zoetis Inc.' },
  // ── Consumer Discretionary ─────────────────────────────────
  { ticker: 'LOW', name: "Lowe's Companies" },
  { ticker: 'NKE', name: 'Nike Inc.' },
  { ticker: 'SBUX', name: 'Starbucks Corp.' },
  { ticker: 'MCD', name: "McDonald's Corp." },
  { ticker: 'YUM', name: 'Yum! Brands' },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill' },
  { ticker: 'DPZ', name: "Domino's Pizza" },
  { ticker: 'QSR', name: 'Restaurant Brands International' },
  { ticker: 'WING', name: 'Wingstop Inc.' },
  { ticker: 'SHAK', name: 'Shake Shack Inc.' },
  { ticker: 'TJX', name: 'TJX Companies' },
  { ticker: 'ROST', name: 'Ross Stores' },
  { ticker: 'BURL', name: 'Burlington Stores' },
  { ticker: 'GPS', name: 'Gap Inc.' },
  { ticker: 'AEO', name: 'American Eagle Outfitters' },
  { ticker: 'ANF', name: 'Abercrombie & Fitch' },
  { ticker: 'LULU', name: 'Lululemon Athletica' },
  { ticker: 'UAA', name: 'Under Armour (Class A)' },
  { ticker: 'VFC', name: 'VF Corp.' },
  { ticker: 'RL', name: 'Ralph Lauren' },
  { ticker: 'TPR', name: 'Tapestry Inc.' },
  { ticker: 'CPRI', name: 'Capri Holdings' },
  { ticker: 'F', name: 'Ford Motor Co.' },
  { ticker: 'GM', name: 'General Motors' },
  { ticker: 'RIVN', name: 'Rivian Automotive' },
  { ticker: 'LCID', name: 'Lucid Group' },
  { ticker: 'NIO', name: 'NIO Inc.' },
  { ticker: 'LI', name: 'Li Auto Inc.' },
  { ticker: 'XPEV', name: 'XPeng Inc.' },
  { ticker: 'HD', name: 'Home Depot Inc.' },
  { ticker: 'LOW', name: "Lowe's Companies" },
  { ticker: 'BBY', name: 'Best Buy Co.' },
  { ticker: 'WSM', name: 'Williams-Sonoma' },
  { ticker: 'RH', name: 'RH (Restoration Hardware)' },
  { ticker: 'W', name: 'Wayfair Inc.' },
  { ticker: 'ETSY', name: 'Etsy Inc.' },
  { ticker: 'EBAY', name: 'eBay Inc.' },
  // ── Consumer Staples ───────────────────────────────────────
  { ticker: 'WMT', name: 'Walmart Inc.' },
  { ticker: 'COST', name: 'Costco Wholesale' },
  { ticker: 'TGT', name: 'Target Corp.' },
  { ticker: 'KR', name: 'Kroger Co.' },
  { ticker: 'SYY', name: 'Sysco Corp.' },
  { ticker: 'PG', name: 'Procter & Gamble' },
  { ticker: 'KO', name: 'Coca-Cola Co.' },
  { ticker: 'PEP', name: 'PepsiCo Inc.' },
  { ticker: 'PM', name: 'Philip Morris International' },
  { ticker: 'MO', name: 'Altria Group' },
  { ticker: 'BTI', name: 'British American Tobacco' },
  { ticker: 'MDLZ', name: 'Mondelez International' },
  { ticker: 'CL', name: 'Colgate-Palmolive' },
  { ticker: 'KMB', name: 'Kimberly-Clark' },
  { ticker: 'CHD', name: 'Church & Dwight' },
  { ticker: 'CLX', name: 'Clorox Co.' },
  { ticker: 'EL', name: 'Estee Lauder Companies' },
  { ticker: 'ULTA', name: 'Ulta Beauty' },
  { ticker: 'KHC', name: 'Kraft Heinz Co.' },
  { ticker: 'GIS', name: 'General Mills' },
  { ticker: 'K', name: "Kellogg's (WK Kellogg)" },
  { ticker: 'CPB', name: "Campbell Soup Co." },
  { ticker: 'HRL', name: 'Hormel Foods' },
  { ticker: 'TSN', name: 'Tyson Foods' },
  { ticker: 'CAG', name: 'Conagra Brands' },
  { ticker: 'MKC', name: 'McCormick & Co.' },
  { ticker: 'STZ', name: 'Constellation Brands' },
  { ticker: 'BUD', name: 'Anheuser-Busch InBev' },
  { ticker: 'TAP', name: 'Molson Coors Beverage' },
  { ticker: 'SAM', name: 'Boston Beer Co.' },
  // ── Energy ─────────────────────────────────────────────────
  { ticker: 'XOM', name: 'Exxon Mobil Corp.' },
  { ticker: 'CVX', name: 'Chevron Corp.' },
  { ticker: 'COP', name: 'ConocoPhillips' },
  { ticker: 'EOG', name: 'EOG Resources' },
  { ticker: 'PXD', name: 'Pioneer Natural Resources' },
  { ticker: 'DVN', name: 'Devon Energy' },
  { ticker: 'FANG', name: 'Diamondback Energy' },
  { ticker: 'MPC', name: 'Marathon Petroleum' },
  { ticker: 'PSX', name: 'Phillips 66' },
  { ticker: 'VLO', name: 'Valero Energy' },
  { ticker: 'HES', name: 'Hess Corp.' },
  { ticker: 'APA', name: 'APA Corp.' },
  { ticker: 'OXY', name: 'Occidental Petroleum' },
  { ticker: 'SLB', name: 'SLB (Schlumberger)' },
  { ticker: 'HAL', name: 'Halliburton Co.' },
  { ticker: 'BKR', name: 'Baker Hughes Co.' },
  { ticker: 'KMI', name: 'Kinder Morgan' },
  { ticker: 'WMB', name: 'Williams Companies' },
  { ticker: 'OKE', name: 'ONEOK Inc.' },
  { ticker: 'LNG', name: 'Cheniere Energy' },
  { ticker: 'BP', name: 'BP PLC' },
  { ticker: 'SHEL', name: 'Shell PLC' },
  { ticker: 'TTE', name: 'TotalEnergies SE' },
  { ticker: 'ENB', name: 'Enbridge Inc.' },
  { ticker: 'CNQ', name: 'Canadian Natural Resources' },
  // ── Industrials ────────────────────────────────────────────
  { ticker: 'GE', name: 'GE Aerospace' },
  { ticker: 'HON', name: 'Honeywell International' },
  { ticker: 'CAT', name: 'Caterpillar Inc.' },
  { ticker: 'DE', name: 'Deere & Company' },
  { ticker: 'BA', name: 'Boeing Co.' },
  { ticker: 'LMT', name: 'Lockheed Martin' },
  { ticker: 'RTX', name: 'RTX Corp.' },
  { ticker: 'NOC', name: 'Northrop Grumman' },
  { ticker: 'GD', name: 'General Dynamics' },
  { ticker: 'LHX', name: 'L3Harris Technologies' },
  { ticker: 'HII', name: 'Huntington Ingalls Industries' },
  { ticker: 'TDG', name: 'TransDigm Group' },
  { ticker: 'HWM', name: 'Howmet Aerospace' },
  { ticker: 'SPR', name: 'Spirit AeroSystems' },
  { ticker: 'UPS', name: 'United Parcel Service' },
  { ticker: 'FDX', name: 'FedEx Corp.' },
  { ticker: 'XPO', name: 'XPO Inc.' },
  { ticker: 'SAIA', name: 'Saia Inc.' },
  { ticker: 'ODFL', name: 'Old Dominion Freight' },
  { ticker: 'CSX', name: 'CSX Corp.' },
  { ticker: 'NSC', name: 'Norfolk Southern' },
  { ticker: 'UNP', name: 'Union Pacific' },
  { ticker: 'CP', name: 'Canadian Pacific Kansas City' },
  { ticker: 'CNI', name: 'Canadian National Railway' },
  { ticker: 'DAL', name: 'Delta Air Lines' },
  { ticker: 'UAL', name: 'United Airlines Holdings' },
  { ticker: 'AAL', name: 'American Airlines Group' },
  { ticker: 'LUV', name: 'Southwest Airlines' },
  { ticker: 'ALK', name: 'Alaska Air Group' },
  { ticker: 'JBLU', name: 'JetBlue Airways' },
  { ticker: 'CCL', name: 'Carnival Corp.' },
  { ticker: 'RCL', name: 'Royal Caribbean Cruises' },
  { ticker: 'NCLH', name: 'Norwegian Cruise Line' },
  { ticker: 'MAR', name: 'Marriott International' },
  { ticker: 'HLT', name: 'Hilton Worldwide' },
  { ticker: 'H', name: 'Hyatt Hotels' },
  { ticker: 'MGM', name: 'MGM Resorts International' },
  { ticker: 'LVS', name: 'Las Vegas Sands' },
  { ticker: 'WYNN', name: 'Wynn Resorts' },
  { ticker: 'CZR', name: 'Caesars Entertainment' },
  { ticker: 'MMM', name: '3M Co.' },
  { ticker: 'EMR', name: 'Emerson Electric' },
  { ticker: 'ITW', name: 'Illinois Tool Works' },
  { ticker: 'PH', name: 'Parker Hannifin' },
  { ticker: 'ETN', name: 'Eaton Corp.' },
  { ticker: 'ROK', name: 'Rockwell Automation' },
  { ticker: 'AME', name: 'AMETEK Inc.' },
  { ticker: 'CSGP', name: 'CoStar Group' },
  { ticker: 'VRSK', name: 'Verisk Analytics' },
  { ticker: 'CPRT', name: 'Copart Inc.' },
  { ticker: 'ADP', name: 'Automatic Data Processing' },
  { ticker: 'PAYX', name: 'Paychex Inc.' },
  { ticker: 'CACI', name: 'CACI International' },
  { ticker: 'SAIC', name: 'Science Applications Intl.' },
  // ── Materials ──────────────────────────────────────────────
  { ticker: 'LIN', name: 'Linde PLC' },
  { ticker: 'APD', name: 'Air Products & Chemicals' },
  { ticker: 'SHW', name: 'Sherwin-Williams' },
  { ticker: 'PPG', name: 'PPG Industries' },
  { ticker: 'ECL', name: 'Ecolab Inc.' },
  { ticker: 'IFF', name: 'International Flavors & Fragrances' },
  { ticker: 'DD', name: 'DuPont de Nemours' },
  { ticker: 'DOW', name: 'Dow Inc.' },
  { ticker: 'LYB', name: 'LyondellBasell Industries' },
  { ticker: 'MOS', name: 'Mosaic Co.' },
  { ticker: 'CF', name: 'CF Industries' },
  { ticker: 'NUE', name: 'Nucor Corp.' },
  { ticker: 'STLD', name: 'Steel Dynamics' },
  { ticker: 'X', name: 'U.S. Steel Corp.' },
  { ticker: 'FCX', name: 'Freeport-McMoRan' },
  { ticker: 'NEM', name: 'Newmont Corp.' },
  { ticker: 'GOLD', name: 'Barrick Gold' },
  { ticker: 'AEM', name: 'Agnico Eagle Mines' },
  { ticker: 'WPM', name: 'Wheaton Precious Metals' },
  { ticker: 'AA', name: 'Alcoa Corp.' },
  // ── Real Estate ────────────────────────────────────────────
  { ticker: 'AMT', name: 'American Tower' },
  { ticker: 'PLD', name: 'Prologis Inc.' },
  { ticker: 'EQIX', name: 'Equinix Inc.' },
  { ticker: 'CCI', name: 'Crown Castle Inc.' },
  { ticker: 'SBAC', name: 'SBA Communications' },
  { ticker: 'PSA', name: 'Public Storage' },
  { ticker: 'EXR', name: 'Extra Space Storage' },
  { ticker: 'AVB', name: 'AvalonBay Communities' },
  { ticker: 'EQR', name: 'Equity Residential' },
  { ticker: 'MAA', name: 'Mid-America Apartment' },
  { ticker: 'UDR', name: 'UDR Inc.' },
  { ticker: 'CPT', name: 'Camden Property Trust' },
  { ticker: 'SPG', name: 'Simon Property Group' },
  { ticker: 'O', name: 'Realty Income Corp.' },
  { ticker: 'NNN', name: 'NNN REIT' },
  { ticker: 'VICI', name: 'VICI Properties' },
  { ticker: 'GLPI', name: 'Gaming and Leisure Properties' },
  { ticker: 'WPC', name: 'W. P. Carey Inc.' },
  { ticker: 'VNO', name: 'Vornado Realty Trust' },
  { ticker: 'BXP', name: 'BXP Inc.' },
  { ticker: 'CBRE', name: 'CBRE Group' },
  { ticker: 'JLL', name: 'Jones Lang LaSalle' },
  { ticker: 'ARE', name: 'Alexandria Real Estate' },
  { ticker: 'WELL', name: 'Welltower Inc.' },
  { ticker: 'VTR', name: 'Ventas Inc.' },
  { ticker: 'PEAK', name: 'Healthpeak Properties' },
  // ── Utilities ──────────────────────────────────────────────
  { ticker: 'NEE', name: 'NextEra Energy' },
  { ticker: 'DUK', name: 'Duke Energy' },
  { ticker: 'SO', name: 'Southern Co.' },
  { ticker: 'D', name: 'Dominion Energy' },
  { ticker: 'AEP', name: 'American Electric Power' },
  { ticker: 'XEL', name: 'Xcel Energy' },
  { ticker: 'PCG', name: 'PG&E Corp.' },
  { ticker: 'EXC', name: 'Exelon Corp.' },
  { ticker: 'ED', name: 'Consolidated Edison' },
  { ticker: 'WEC', name: 'WEC Energy Group' },
  { ticker: 'DTE', name: 'DTE Energy' },
  { ticker: 'ETR', name: 'Entergy Corp.' },
  { ticker: 'AWK', name: 'American Water Works' },
  { ticker: 'CNP', name: 'CenterPoint Energy' },
  { ticker: 'NI', name: 'NiSource Inc.' },
  // ── Broad Market & Index ETFs ──────────────────────────────
  { ticker: 'SPY', name: 'SPDR S&P 500 ETF' },
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF' },
  { ticker: 'IVV', name: 'iShares Core S&P 500 ETF' },
  { ticker: 'QQQ', name: 'Invesco Nasdaq-100 ETF' },
  { ticker: 'QQQM', name: 'Invesco Nasdaq-100 ETF (Mini)' },
  { ticker: 'IWM', name: 'iShares Russell 2000 ETF' },
  { ticker: 'IWF', name: 'iShares Russell 1000 Growth ETF' },
  { ticker: 'IWD', name: 'iShares Russell 1000 Value ETF' },
  { ticker: 'VTI', name: 'Vanguard Total Stock Market ETF' },
  { ticker: 'VXF', name: 'Vanguard Extended Market ETF' },
  { ticker: 'MDY', name: 'SPDR S&P MidCap 400 ETF' },
  { ticker: 'IJH', name: 'iShares Core S&P Mid-Cap ETF' },
  { ticker: 'IJR', name: 'iShares Core S&P Small-Cap ETF' },
  { ticker: 'DIA', name: 'SPDR Dow Jones Industrial ETF' },
  { ticker: 'RSP', name: 'Invesco S&P 500 Equal Weight ETF' },
  { ticker: 'SCHB', name: 'Schwab US Broad Market ETF' },
  { ticker: 'SCHX', name: 'Schwab US Large-Cap ETF' },
  // ── Sector ETFs ────────────────────────────────────────────
  { ticker: 'XLK', name: 'Technology Select Sector SPDR' },
  { ticker: 'XLF', name: 'Financial Select Sector SPDR' },
  { ticker: 'XLE', name: 'Energy Select Sector SPDR' },
  { ticker: 'XLV', name: 'Health Care Select Sector SPDR' },
  { ticker: 'XLY', name: 'Consumer Discretionary SPDR' },
  { ticker: 'XLP', name: 'Consumer Staples Select Sector SPDR' },
  { ticker: 'XLI', name: 'Industrial Select Sector SPDR' },
  { ticker: 'XLB', name: 'Materials Select Sector SPDR' },
  { ticker: 'XLU', name: 'Utilities Select Sector SPDR' },
  { ticker: 'XLRE', name: 'Real Estate Select Sector SPDR' },
  { ticker: 'XLC', name: 'Communication Services SPDR' },
  { ticker: 'VGT', name: 'Vanguard Information Tech ETF' },
  { ticker: 'VHT', name: 'Vanguard Health Care ETF' },
  { ticker: 'VFH', name: 'Vanguard Financials ETF' },
  { ticker: 'VDE', name: 'Vanguard Energy ETF' },
  { ticker: 'SOXX', name: 'iShares Semiconductor ETF' },
  { ticker: 'SMH', name: 'VanEck Semiconductor ETF' },
  { ticker: 'SKYY', name: 'First Trust Cloud Computing ETF' },
  { ticker: 'WCLD', name: 'WisdomTree Cloud Computing ETF' },
  { ticker: 'IGV', name: 'iShares Expanded Tech-Software ETF' },
  { ticker: 'HACK', name: 'ETFMG Prime Cyber Security ETF' },
  { ticker: 'CIBR', name: 'First Trust Cybersecurity ETF' },
  { ticker: 'ROBO', name: 'ROBO Global Robotics & Automation' },
  { ticker: 'BOTZ', name: 'Global X Robotics & AI ETF' },
  { ticker: 'AIQ', name: 'Global X AI & Technology ETF' },
  { ticker: 'CLOU', name: 'Global X Cloud Computing ETF' },
  { ticker: 'FINX', name: 'Global X FinTech ETF' },
  { ticker: 'LIT', name: 'Global X Lithium & Battery Tech ETF' },
  { ticker: 'ICLN', name: 'iShares Global Clean Energy ETF' },
  { ticker: 'QCLN', name: 'First Trust NASDAQ Clean Edge ETF' },
  { ticker: 'TAN', name: 'Invesco Solar ETF' },
  { ticker: 'FAN', name: 'First Trust Global Wind Energy ETF' },
  { ticker: 'ARKG', name: 'ARK Genomic Revolution ETF' },
  { ticker: 'ARKW', name: 'ARK Next Generation Internet ETF' },
  { ticker: 'ARKF', name: 'ARK Fintech Innovation ETF' },
  { ticker: 'ARKK', name: 'ARK Innovation ETF' },
  // ── International ETFs ─────────────────────────────────────
  { ticker: 'VEA', name: 'Vanguard Developed Markets ETF' },
  { ticker: 'VWO', name: 'Vanguard FTSE Emerging Markets ETF' },
  { ticker: 'EFA', name: 'iShares MSCI EAFE ETF' },
  { ticker: 'EEM', name: 'iShares MSCI Emerging Markets ETF' },
  { ticker: 'IEFA', name: 'iShares Core MSCI EAFE ETF' },
  { ticker: 'IEMG', name: 'iShares Core MSCI Emerging Markets' },
  { ticker: 'EWJ', name: 'iShares MSCI Japan ETF' },
  { ticker: 'EWZ', name: 'iShares MSCI Brazil ETF' },
  { ticker: 'EWC', name: 'iShares MSCI Canada ETF' },
  { ticker: 'EWG', name: 'iShares MSCI Germany ETF' },
  { ticker: 'EWU', name: 'iShares MSCI United Kingdom ETF' },
  { ticker: 'KWEB', name: 'KraneShares CSI China Internet ETF' },
  { ticker: 'MCHI', name: 'iShares MSCI China ETF' },
  { ticker: 'FXI', name: 'iShares China Large-Cap ETF' },
  { ticker: 'INDA', name: 'iShares MSCI India ETF' },
  // ── Fixed Income ETFs ──────────────────────────────────────
  { ticker: 'TLT', name: 'iShares 20+ Year Treasury ETF' },
  { ticker: 'IEF', name: 'iShares 7-10 Year Treasury ETF' },
  { ticker: 'SHY', name: 'iShares 1-3 Year Treasury ETF' },
  { ticker: 'BND', name: 'Vanguard Total Bond Market ETF' },
  { ticker: 'AGG', name: 'iShares Core US Aggregate Bond ETF' },
  { ticker: 'LQD', name: 'iShares iBoxx Investment Grade ETF' },
  { ticker: 'HYG', name: 'iShares High Yield Corp Bond ETF' },
  { ticker: 'JNK', name: 'SPDR Bloomberg High Yield Bond ETF' },
  { ticker: 'MUB', name: 'iShares National Muni Bond ETF' },
  { ticker: 'TIPS', name: 'iShares TIPS Bond ETF' },
  { ticker: 'VCIT', name: 'Vanguard Intermediate-Term Corp Bond' },
  { ticker: 'VCSH', name: 'Vanguard Short-Term Corp Bond ETF' },
  { ticker: 'BNDX', name: 'Vanguard Total Intl Bond ETF' },
  // ── Commodity ETFs ─────────────────────────────────────────
  { ticker: 'GLD', name: 'SPDR Gold Shares' },
  { ticker: 'IAU', name: 'iShares Gold Trust' },
  { ticker: 'GLDM', name: 'SPDR Gold MiniShares' },
  { ticker: 'SLV', name: 'iShares Silver Trust' },
  { ticker: 'PPLT', name: 'Aberdeen Physical Platinum ETF' },
  { ticker: 'PALL', name: 'Aberdeen Physical Palladium ETF' },
  { ticker: 'USO', name: 'United States Oil Fund' },
  { ticker: 'UNG', name: 'United States Natural Gas Fund' },
  { ticker: 'DBA', name: 'Invesco DB Agriculture Fund' },
  { ticker: 'DBB', name: 'Invesco DB Base Metals Fund' },
  { ticker: 'PDBC', name: 'Invesco Optimum Yield Diversified Commodity' },
  // ── Leveraged & Inverse ETFs ───────────────────────────────
  { ticker: 'TQQQ', name: 'ProShares UltraPro QQQ (3x)' },
  { ticker: 'SQQQ', name: 'ProShares UltraPro Short QQQ (3x inverse)' },
  { ticker: 'UPRO', name: 'ProShares UltraPro S&P 500 (3x)' },
  { ticker: 'SPXU', name: 'ProShares UltraPro Short S&P 500 (3x inverse)' },
  { ticker: 'SSO', name: 'ProShares Ultra S&P 500 (2x)' },
  { ticker: 'SDS', name: 'ProShares UltraShort S&P 500 (2x inverse)' },
  { ticker: 'QLD', name: 'ProShares Ultra QQQ (2x)' },
  { ticker: 'PSQ', name: 'ProShares Short QQQ (1x inverse)' },
  { ticker: 'SH', name: 'ProShares Short S&P 500 (1x inverse)' },
  { ticker: 'UVXY', name: 'ProShares Ultra VIX Short-Term Futures' },
  { ticker: 'SVXY', name: 'ProShares Short VIX Short-Term Futures' },
  { ticker: 'LABU', name: 'Direxion Daily S&P Biotech Bull 3x' },
  { ticker: 'LABD', name: 'Direxion Daily S&P Biotech Bear 3x' },
  { ticker: 'SOXL', name: 'Direxion Daily Semiconductor Bull 3x' },
  { ticker: 'SOXS', name: 'Direxion Daily Semiconductor Bear 3x' },
  { ticker: 'FAS', name: 'Direxion Daily Financial Bull 3x' },
  { ticker: 'FAZ', name: 'Direxion Daily Financial Bear 3x' },
  { ticker: 'TECL', name: 'Direxion Daily Technology Bull 3x' },
  { ticker: 'TECS', name: 'Direxion Daily Technology Bear 3x' },
  // ── Volatility & Alternatives ──────────────────────────────
  { ticker: 'VXX', name: 'iPath S&P 500 VIX Short-Term Futures' },
  { ticker: 'VIXY', name: 'ProShares VIX Short-Term Futures ETF' },
]

/**
 * Filter ticker list based on user input.
 * Matches ticker prefix first, then company name substring.
 * Returns up to `limit` results.
 */
export function searchTickers(query, limit = 8) {
  if (!query || query.length < 1) return []
  const q = query.toUpperCase()

  const seen = new Set()
  const tickerMatches = []
  const nameMatches = []

  for (const t of TICKER_LIST) {
    if (seen.has(t.ticker)) continue
    seen.add(t.ticker)
    if (t.ticker.startsWith(q)) {
      tickerMatches.push(t)
    } else if (t.name.toUpperCase().includes(q)) {
      nameMatches.push(t)
    }
  }

  return [...tickerMatches, ...nameMatches].slice(0, limit)
}
